---
- name: "Check for elasticsearch_exporter binary"
  stat:
    path: "/usr/local/bin/elasticsearch_exporter"
  changed_when: false
  register: elasticsearch_exporter_install

- when: not elasticsearch_exporter_install.stat.exists
  block:
    - name: "Download elasticsearch_exporter..."
      get_url:
        url: '{{ es_exporter_tgz_url }}'
        dest: /tmp/{{ es_exporter_tgz }}
        timeout: 120
        mode: 0644

    - name: "Ensure install directory exists"
      file:
        path: '{{ es_exporter_install_dir }}'
        state: directory

    - name: "Unarchive elasticsearch_exporter..."
      unarchive:
        remote_src: yes
        src: /tmp/{{ es_exporter_tgz }}
        dest: '{{ es_exporter_install_dir }}'
        extra_opts: [--strip-components=1]

    - name: Copy elasticsearch_exporter binary..."
      copy:
        src: '{{ es_exporter_install_dir }}/elasticsearch_exporter'
        dest: '/usr/local/bin/elasticsearch_exporter'
        mode: '0755'
        remote_src: yes

- name: "Create systemd for elasticsearch_exporter"
  template:
    src: elasticsearch_exporter.service.j2
    dest: /etc/systemd/system/elasticsearch_exporter.service
    mode: '0640'
  notify: "restart elasticsearch_exporter"

- name: "Enable and Start elasticsearch_exporter.service"
  systemd:
    name: elasticsearch_exporter
    state: started
    enabled: true
    daemon_reload: true
